using System.ComponentModel.DataAnnotations.Schema;
using API.Entities;
using Microsoft.EntityFrameworkCore;

namespace API.Data
{
    [Table("Photos")]
    //to create table photos, and it's used with user
        public class DataContext : DbContext
    {
        public DataContext(DbContextOptions options) : base(options)
        {
        }

        public DbSet<AppUser> Users { get; set; }
        //in this case users is our table name..
        // also it generated by Migrations
        // it means we're writing our code by code first not db first!
    

    }
}